// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcnZabbVwgpCVK1kDOTmVYu3pyCwD67ZQ',
    appId: '1:420531780354:web:6787b5bd832273a854601b',
    messagingSenderId: '420531780354',
    projectId: 'travel-app-9c987',
    authDomain: 'travel-app-9c987.firebaseapp.com',
    storageBucket: 'travel-app-9c987.appspot.com',
    measurementId: 'G-6ZXCG72S59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD063KFA4B6HPqdUuQTIcle2LvS2GD2qzE',
    appId: '1:420531780354:android:d4c4d788469051cb54601b',
    messagingSenderId: '420531780354',
    projectId: 'travel-app-9c987',
    storageBucket: 'travel-app-9c987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjJkaBOf3uNBMSg7yGINzqPrUAbrv2bM',
    appId: '1:420531780354:ios:3860785c5e43f75254601b',
    messagingSenderId: '420531780354',
    projectId: 'travel-app-9c987',
    storageBucket: 'travel-app-9c987.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjjJkaBOf3uNBMSg7yGINzqPrUAbrv2bM',
    appId: '1:420531780354:ios:3860785c5e43f75254601b',
    messagingSenderId: '420531780354',
    projectId: 'travel-app-9c987',
    storageBucket: 'travel-app-9c987.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcnZabbVwgpCVK1kDOTmVYu3pyCwD67ZQ',
    appId: '1:420531780354:web:b0c9d2a19a81cc1b54601b',
    messagingSenderId: '420531780354',
    projectId: 'travel-app-9c987',
    authDomain: 'travel-app-9c987.firebaseapp.com',
    storageBucket: 'travel-app-9c987.appspot.com',
    measurementId: 'G-2ZEDPCQECB',
  );
}
